package com.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldWS", targetNamespace = "http://services.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorldWS
{

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String goToHell();

}
