
package com.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldImpService", targetNamespace = "http://services.com/", wsdlLocation = "http://localhost:8080/testWS/hello?wsdl")
public class HelloWorldImpService
    extends Service
{

    private final static URL HELLOWORLDIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDIMPSERVICE_EXCEPTION;
    private final static QName HELLOWORLDIMPSERVICE_QNAME = new QName("http://services.com/", "HelloWorldImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/testWS/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDIMPSERVICE_WSDL_LOCATION = url;
        HELLOWORLDIMPSERVICE_EXCEPTION = e;
    }

    public HelloWorldImpService() {
        super(__getWsdlLocation(), HELLOWORLDIMPSERVICE_QNAME);
    }

    public HelloWorldImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDIMPSERVICE_QNAME, features);
    }

    public HelloWorldImpService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDIMPSERVICE_QNAME);
    }

    public HelloWorldImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDIMPSERVICE_QNAME, features);
    }

    public HelloWorldImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldWS
     */
    @WebEndpoint(name = "HelloWorldImpPort")
    public HelloWorldWS getHelloWorldImpPort() {
        return super.getPort(new QName("http://services.com/", "HelloWorldImpPort"), HelloWorldWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldWS
     */
    @WebEndpoint(name = "HelloWorldImpPort")
    public HelloWorldWS getHelloWorldImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.com/", "HelloWorldImpPort"), HelloWorldWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDIMPSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDIMPSERVICE_EXCEPTION;
        }
        return HELLOWORLDIMPSERVICE_WSDL_LOCATION;
    }

}
